package main

var ferengi = []string{
	`Once you have their money, never give it back`,
	`You can't cheat an honest customer, but it never hurts to try`,
	`Never spend more for an acquisition than you have to`,
	`Sex and profit are the two things that never last long enough`,
	`If you can't break a contract, bend it`,
	`Never let family stand in the way of opportunity`,
	`Always keep you ears open`,
	`Keep count of your change`,
	`Instinct plus opportunity equals profit`,
	`A dead customer can't buy as much as a live one`,
	`Latinum isn't the only thing that shines`,
	`Anything worth selling is worth selling twice`,
	`Anything worth doing is worth doing for money`,
	`Anything stolen is pure profit`,
	`Acting stupid is often smart`,
	`A deal is a deal ... until a better one comes along`,
	`A bargain usually isn't`,
	`A Ferengi without profit is no Ferengi at all`,
	`Don't lie too soon after a promotion`,
	`When the customer is sweating, turn up the heat`,
	`Never place friend ship before profit`,
	`Wise men can hear profit in the wind`,
	`Never take the last coin, but be sure to get the rest`,
	`Never ask when you can take`,
	`Fear makes a good business partner`,
	`The vast majority of the rich in this galaxy did not inherit their wealth; they stole it`,
	`The most beautiful thing about a tree is what you do with it after you cut it down`,
	`Morality is always defined by those in power`,
	`When someone says "It's not the money," they're lying`,
	`Talk is cheap; synthehol costs money`,
	`Never make fun of a Ferengi's mother`,
	`Be careful what you sell. It may do exactly what the customer expects`,
	`It never hurts to suck up to the boss`,
	`War is good for business`,
	`Peace is good for business`,
	`Too many Ferengi can't laugh at themselves anymore`,
	`You can always buy back a lost reputation`,
	`Free advertising is cheap`,
	`Praise is cheap. Heap it generously on all customers`,
	`If you see profit on a journey, take it`,
	`Money talks, but having a lots of it gets more attention`,
	`Only negotiate when you are certain to profit`,
	`Caressing an ear is often more forceful than pointing a weapon`,
	`Never argue with a loaded phaser`,
	`Profit has limits. Loss has none`,
	`Labor camps are full of people who trusted the wrong person`,
	`Never trust a man wearing a better suit than you own`,
	`The bigger the smile, the sharper the knife`,
	`Old age and greed will always overcome youth and talent`,
	`Never bluff a Klingon`,
	`Never admit a mistake if there's someone else to blame`,
	`Only Bugsy could have built Las Vegas`,
	`Sell first; ask questions later`,
	`Skape Games - Pokemon TCG and more!`,
	`Never buy anything you can't sell`,
	`Always sell at the highest possible profit`,
	`Pursue profit; women come later`,
	`Good customers are almost as rare as Latinum - treasure them`,
	`Friendship is seldom cheap`,
	`Fee advice is never cheap`,
	`Never use Latinum where your words will do`,
	`Never buy what can be stolen`,
	`The riskier the road, the greater the profit`,
	`Power without profit is like a ship without an engine`,
	`Don't talk shop; talk shopping`,
	`Don't talk ship; talk shipping`,
	`Anyone serving in a fleet who is crazy can be relieved, if they ask for it`,
	`Enough is never enough`,
	`Compassion is no substitute for a profit`,
	`You could afford your ship without your government - if it weren't for your government`,
	`Get the money first, then let the buyers worry about collecting the merchandise`,
	`Gamble and trade have two things in common: risk and Latinum`,
	`Never let the competition know, what you're thinking`,
	`Never trust advice from a dying Ferengi; listen but don't trust`,
	`A Ferengi without profit is no Ferengi at all`,
	`Home is where the heart is, but the stars are made of Latinum`,
	`Every once in a while, declare peace. It confuses the hell out of your enemies`,
	`Go where no Ferengi has gone before; where there is no reputation there is profit`,
	`Don't discriminate. The most unlikely species can create the best customers`,
	`Benefit from the Vulcan greed for knowledge`,
	`If it works, sell it. If it works well, sell it for more. If it doesn't work, quadruple the price and sell it as an antique`,
	`There's nothing more dangerous than an honest businessman`,
	`A smart customer is not a good customer`,
	`Revenge is profitless`,
	`She can touch your ears but never your Latinum`,
	`Death takes no bribes`,
	`A wife is a luxury, a smart accountant a necessity`,
	`Trust is the biggest liability of all`,
	`When the boss comes to dinner, it never hurts to have the wife wear something`,
	`Latinum lasts longer than lust`,
	`Mine is better than ours`,
	`He who drinks fast pays slow`,
	`Never confuse wisdom with luck`,
	`He's a fool who makes his doctor his heir`,
	`Beware of small expenses: a small leak will kill a ship`,
	`Important, more impotant, Latinum`,
	`Faith moves mountains - of inventory`,
	`If you would keep a secret from an enemy, don't tell it to a friend`,
	`Profit is the better part of valor`,
	`Never trust a wise man`,
	`Everything that has no owner, needs one`,
	`Never do something you can make someone do for you`,
	`Nature decays, but Latinum lasts forever`,
	`Sleep can interfere with opportunity`,
	`Money is never made. It is merely won or lost`,
	`Wise men don't lie, they just bend the truth`,
	`There is no honor in poverty`,
	`Win or lose, there's always Huyperian Beetle Snuff`,
	`A woman wearing clothes is like a man without profit`,
	`Dignity and an empty sack is worth the sack`,
	`Only a fool passes up a business opportunity`,
	`Treat people in your debt like family ... exploit them`,
	`Never sleep with the boss's wife unless you pay him first`,
	`Never sleep with the boss's sister`,
	`Small print lead to large risk`,
	`Greed is eternal`,
	`There's always a way out`,
	`If the profit seems too good to be true, it usually is`,
	`Never cheat a honest man offering a decent price`,
	`Buy, sell, or get out of the way`,
	`Even a blind man can recognize the glow of Latinum`,
	`Everything is for sale, even friendship`,
	`As the customers go, so goes the wise profiteer`,
	`A friend is only a friend until you sell him something. Then he is a customer`,
	`Friendship is temporary, profit is forever`,
	`eck out the brand new StarTrek Game - Especially for StarTrek Fans!`,
	`A lie isn't a lie until someone else knows the truth`,
	`A lie isn't a lie, it's just the truth seen from a different point of view`,
	`Gratitude can bring on generosity`,
	`Ferengi are not responsible for the stupidity of other races`,
	`Never trust your customers`,
	`Never trust a beneficiary`,
	`If it gets you profit, sell your own mother`,
	`The flimsier the produce, the higher the price`,
	`Never judge a customer by the size of his wallet ... sometimes good things come in small packages`,
	`There's always a catch`,
	`The only value of a collectible is what you can get somebody else to pay for it`,
	`The sharp knife cuts quickly. Act without delay!`,
	`Necessity is the mother of invention. Profit is the father`,
	`Law makes everyone equal, but justice goes to the highest bidder`,
	`Wives serve; brother inherit`,
	`The answer to quick and easy profit is: buy for less, sell for more`,
	`Competition and fair play are mutually exclusive. Fair play and financial loss go hand-in-hand`,
	`A Ferengi waits to bid until his opponents have exhausted themselves`,
	`The family of Fools is ancient`,
	`There's nothing wrong with charity ... as long as it winds up in your pocket`,
	`Always ask for the costs first`,
	`If possible sell neither the sizzle nor the steak, but the Elphasian wheat germ`,
	`New customers are like razor toothed gree worms. They can be succulent, but sometimes they bite back`,
	`Opportunity waits for no one`,
	`Females and finances don't mix`,
	`Make your shop easy to find`,
	`Sometimes, what you get free costs entirely too much`,
	`Ask not what your profits can do for you; ask what you can do for your profits`,
	`You can't free a fish from water`,
	`The difference between manure and Latinum is commerece`,
	`What's mine is mine, and what's yours is mine too`,
	`Even in the worst of times someone turns a profit`,
	`You are surrounded by opportunities; you just have to know where to look`,
	`Don't pay until you have the goods`,
	`The customer is always right ... until you have their cash`,
	`Respect is good, Latinum is better`,
	`Never kill a customer, unless you make more profit out of his death than out of his life`,
	`His money is only your's when he can't get it back`,
	`A thirsty customer is good for profit, a drunk one isn't`,
	`Never spend your own money when you can spend someone elses`,
	`Never allow one's culture's law to get in the way of a universal goal: profit`,
	`Never give away for free what can be sold`,
	`If a deal is fairly and lawfully made, then seeking revenge especially unprofitable revenge, is illegal`,
	`Beware of relatives bearing gifts`,
	`If you're going to have to endure, make yourself comfortable`,
	`Never gamble with an empath`,
	`Time is Latinum. The early Ferengi get the Latinum`,
	`If you can sell it, don't hsitate to steal it`,
	`A piece of Latinum in the hand is worth two in a customer's pocket`,
	`Share and perish`,
	`When everything fails - run`,
	`Ferengi's don't give promotional gifts!`,
	`Know your enemies ... but do business with them always`,
	`The world is a stage - don't forget to demand admission`,
	`Whenever you think that things can't get worse, the FCA will be knocking on you door`,
	`Never offer a confession when a bribe will do`,
	`Even dishonesty can't tarnish the glow of Latinum`,
	`Whenever you're being asked if you are god, the right answer is YES`,
	`Genius without opportunity is like Latinum in the mine`,
	`There are three things you must not talk to aliens: sex, religion and taxes`,
	`If you want to ruin yourself there are three known ways: Gambling is the fastest, women are the sweetest, and banks are the most reliable way`,
	`There are two things that will catch up with you for sure: death and taxes`,
	`If your dancing partner wants to lead at all costs, let her have her own way and ask another one to dance`,
	`Never bet on a race you haven't fixed`,
	`Borrow on a handshake; lend in writing`,
	`Drive your business or it will drive you`,
	`Let other keep their reputation. You keep their money`,
	`If the flushing isn't strong enough, use your brain and try the brush`,
	`Klingon women don't dance tango`,
	`It's always good business to know about new customers before they walk in your door`,
	`Wounds heal, but debt is forever`,
	`Only give money to people you know you can steal from`,
	`Never trust your customers, especially if they are your relatives`,
	`Employees are the rungs on your ladder to success - don't hesitate to step on them`,
	`The secret of one person is another person's opportunity`,
	`A madman with Latinum means profit without return`,
	`The justification for profit is profit`,
	`A friend in need is a customer in the making`,
	`A friend in need means three times the profit`,
	`A Ferengi in need, will never do anything for free`,
	`When the Grand Nagus arrives to offer you a business opportunity, it's time to leave town until he's gone`,
	`When the customer dies, the money stops a-comin'`,
	`Fighting with Klingons is like gambling with Cardassians - it's good to have a friend around when you lose`,
	`Never trust a hardworking employee`,
	`Give someone a fish, you feed him for one day.  Teach him how to fish, and you lose a steady customer`,
	`Tell them what they want to hear`,
	`A wife, who is able to clean, saves the cleaning lady`,
	`In business deals, a disruptor can be almost as important as a calculator`,
	`If they accept your first offer, you either asked too little or offered too much`,
	`Stay neutral in conflicts so that you can sell supplies to both sides`,
	`Never begin a business transaction on an empty stomach`,
	`Instinct without opportunity is useless`,
	`Never take hospitality from someone worse off than yourself`,
	`Only pay for it if you are confronted with loaded phaser`,
	`Always know what you're buying`,
	`A friend is not a friend if he asks for a discount`,
	`Profit is like a bed of roses - a few thorns are inevitable`,
	`Beware of any man who thinks with his lobes`,
	`Knowledge is Latinum`,
	`has finally become logical`,
	`Rich men don't come to buy; they come to take`,
	`Never throw anything away: It may be worht a lot of Latinum some Stardate`,
	`Pride comes before a loss`,
	`Don't take your family for granted, only their Latinum`,
	`Loyalty can be bought ... and sold`,
	`All things come to those who wait, even Latinum`,
	`Beware the man who doesn't make time for oo-mox`,
	`Manipulation may be a Ferengi's greatest tool, and liability`,
	`If you steal it, make sure it has a warranty`,
	`Life's no fair (How else would you turn a profit?)`,
	`Every dark cloud has a Latinum lining`,
	`Never deal with beggars; it's bad for profits`,
	`Don't trust anyone who trusts you`,
	`You can't buy fate`,
	`There's a sucker born every minute.  Be sure you're the first to find each one`,
	`The truth will cost`,
	`Ambition knows no family`,
	`The higher you bid, the more customers you drive away`,
	`Never underestimate the inportance of the fist impression`,
	`More is good, all is better`,
	`If you got something nice to say, then SHOUT`,
	`If you can't sell it, sit on it, but never give it away`,
	`A warranty is valid only if they can find you`,
	`He that speaks ill of the wares will buy them`,
	`Never question luck`,
	`Celebrate when you are paid, not, when you are promised`,
	`Respect other culture's beliefs; they'll be more likely to give you money`,
	`A dead vendor doesn't demand money`,
	`Satisfaction is not guaranteed`,
	`Let the buyer beware`,
	`A contract without fine print is a fool's document`,
	`Anyone who can't tell a fake doesn't deserve the real thing`,
	`A warranty without loop-holes is a liability`,
	`Synthehol is the lubricant of choice for a customer's stuck purse`,
	`Only fools negotiate with their own money`,
	`A Ferengi is only as important as the amount of Latinum he carries in his pockets`,
	`A lie is a way to tell the truth to someone who doesn't know`,
	`Gambling is like the way to power: The only way to win is to cheat, but don't get caught in the process`,
	`A wealthy man can afford everything except a conscience`,
	`No lobes, no profit`,
	`Never let a female in clothes cloud your sense of profit`,
	`It's not the size of your planet, but it's income, that matters`,
	`The fear of loss may be your greatest enemy or your best friend - choose wisely`,
	`A pair of good ears will ring dry a hundred tongues`,
	`Wish not so much to live Long, as to live well`,
	`When in doubt, lie`,
	`When in doubt, buy`,
	`When in doubt, demand more money`,
	`When in doubt, shoot them, take their money, run and blame someone else`,
	`Never purchase anything that has been promised to be valuable or go up in value`,
	`It's better to have gambled and lost than to never have gambled at all`,
	`There's many witty men whose brains can't line their pockets`,
	`The way to a Ferengi's heart is through his wallet`,
	`Always count their Latinum before selling anything`,
	`There is no profit in love; however, a strong heart is worth a few bars of Latinum on the open market. Keep it on ice`,
	`Latinum can't buy happiness, but you can sure have a blast renting it`,
	`If at first you don't succeed, try to acquire again`,
	`Diamonds may be girl's best friend, but you can only buy the girl with Latinum`,
	`It's better to swallow your pride than to lose your profit`,
	`Never close a deal too soon after a female strokes your lobes`,
	`An empty bag can not stand upright`,
	`Blood is thicker than water, but harder to sell`,
	`Business is like war; it's important to recognize the winner`,
	`Rules are always subject to change`,
	`Rules are always subject to interpretation`,
	`No good deed ever goes unpunished`,
	`When Morn leaves it is all over`,
}
